kibot:
    version: 1

globals:
    dir: generated

preflight:
    check_zone_fills: true
    erc:
        filters:
            - error: lib_symbol_issues
    drc:
        filters:
            - error: lib_footprint_issues

outputs:
    - name: pcbdraw
      type: pcbdraw
