kibot:
    version: 1

globals:
    dir: generated

preflight:
    check_zone_fills: true
    erc: true
    drc: true
    filters:
        - error: lib_footprint_issues
        - error: lib_symbol_issues

outputs:
    - name: pcbdraw
      type: pcbdraw
