name: "Variants demo using GitHub actions and quick-start"

on: [push]

jobs:
  kibot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: speedo-pcb/config.kibot.yaml